[package]

name = "bio"
version = "0.3.18"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics."
homepage = "https://github.com/johanneskoester/rust-bio"
readme = "README.md"
license = "MIT"

[dependencies]
csv = ">=0.14.3"
rustc-serialize = ">=0.3.16"
num = ">=0.1.27"
itertools = ">=0.4.1"
bit-vec = ">=0.4.2"
vec_map = ">=0.3.0"
bit-set = ">=0.2.0"
nalgebra= "*"
lazy_static = "0.1.*"
